version: "3"
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        USER_UID: 1000
        WORKDIR: /package
    image: mtpublishers-core-dev:0.1.0
    container_name: mtpublishers-core-dev
    user: vscode
    volumes:
      - "${PWD}:/package"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8888"
    env_file:
      - .env
    networks:
      - default
      - netproxy

networks:
  netproxy:
    external:
      name: netproxy